// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ijUpdate
NumericVector ijUpdate(DataFrame ijDat, NumericVector newPi, DataFrame iDatNew);
RcppExport SEXP _skipTrack_ijUpdate(SEXP ijDatSEXP, SEXP newPiSEXP, SEXP iDatNewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type ijDat(ijDatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type newPi(newPiSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type iDatNew(iDatNewSEXP);
    rcpp_result_gen = Rcpp::wrap(ijUpdate(ijDat, newPi, iDatNew));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_skipTrack_ijUpdate", (DL_FUNC) &_skipTrack_ijUpdate, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_skipTrack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
